messages:
  - msg 1 {random}
  - msg 2 {random}
  - msg 3 {random}
  # - This is a test message
  # You can add as many messages as u want
  # Pro tip: {random} will be replaced with random characters to prevent being detected easily

random_length: 5
# How many random characters should be added to the message in {random}

comment_upload_delay: 30
# Delay in seconds between comment uploads, don't go under 25 with a single IP
